### ISSUE TITLE
Make the Decline button actually decline

### ISSUE THREAD

**Issue by belohnung** [mathhulk/pnrtscr.com#10]
You claim you added a seizure warning "to combat physical harm", which is over the Accept / Decline buttons, yet the Decline button does the same as the Accept button - Jumpscare and potentionally cause harm to someone with Photosensitivity. It feels like you didn't do this because you actually care but more so to stop the Abuse reports.

**Comment by AL1L** [comment]
It's a cookie accept button. It's not declining the jump-scare, it's declining the cookies. Which there are none even if you accept so of course it does the same thing.

@mathhulk pls close
