### ISSUE TITLE
When opening the website it redirects to prnt.sc

### ISSUE THREAD

**Issue by SonicKinder** [mathhulk/pnrtscr.com#11]

**Comment by SonicKinder** [comment]
figured out that when i use the domain to redirect form ddns.net IP to the title, it doesn't work, but when it's the ddns.net ip it works

**Comment by SonicKinder** [comment]
also, the video not playing, it's just the white screen. maybe i need an extension? i heard about magick but i ddin't understand how would i install it. usiing windows server with XAMPP

**Comment by mathhulk** [comment]
The website redirects to `pnrt.sc` if no path is provided. This is intended. Unfortunately, I do not provide support if you are trying to run this project yourself, but the video works properly on `pnrtscr.com`.  I can tell you that you only need PHP to run it, although I have no idea what system you are using.

**Comment by SonicKinder** [comment]
> The website redirects to `pnrt.sc` if no path is provided. This is intended. Unfortunately, I do not provide support if you are trying to run this project yourself, but the video works properly on `pnrtscr.com`. I can tell you that you only need PHP to run it, although I have no idea what system you are using.

i said that i use Windows server, i have the PHP in that too. how do i setup the path for it then?

**Comment by SonicKinder** [comment]
like maybe there's an extension i need to enable in php?
