### ISSUE TITLE
Tutorial how to run

### ISSUE THREAD

**Issue by ghost** [mathhulk/pnrtscr.com#9]
Hi i am Amateur in Programming i just know C and Python so about PHP or HTML idk. so there's an active link or we're the one to reactivate this? If it is then how:

**Comment by ghost** [comment]
I see in reddit post the live link okay and im requesting to upgrade this:) because when i open it my website showing;

"The connection to pnrtscr.com is not secure
You are seeing this warning because this site does not support HTTPS (Continue to Site/Back)"

which user will not continue

I also request if you just want that if this can run by terminal in ubuntu or linux
Example:
$ Git clone pnrtscr
$ Start pnrtscr
$ Generate Link (Generating different links)(Dispose link after use)
$ On/Stop

So the link is not static and not spread it

**Comment by mathhulk** [comment]
Hey! I don’t normally check this repository so I’m sorry for the delayed response. I think you might have tried to access the website while we were facing some issues with hosting, but there shouldn’t be any more problems.

If you’re looking to host this yourself, PHP comes with a [built-in barebones web server](https://www.php.net/manual/en/features.commandline.webserver.php). However, if you’d like to host this for public use, I’d suggest looking into web servers like NGINX or Apache.
